name: Linux-CRD

on:
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true

jobs:

  build:
    name: Built Connection
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Initializing Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        sudo apt-get install -y xdg-utils
        sudo apt-get install -y libxss1
        sudo apt-get install -y libasound2
        sudo apt-get install -y libgtk2.0-0
        sudo apt-get install -y libglib2.0-0
        sudo apt-get install -y libxcursor1
        sudo apt-get install -y libxcomposite1
        sudo apt-get install -y libxi6
        sudo apt-get install -y libxtst6
        sudo apt-get install -y fonts-liberation
        sudo apt-get install -y libappindicator1
        sudo apt-get install -y libcairo2
        sudo apt-get install -y libcups2
        sudo apt-get install -y libexpat1
        sudo apt-get install -y libfontconfig1
        sudo apt-get install -y libgcc1
        sudo apt-get install -y libgdk-pixbuf2.0-0
        sudo apt-get install -y libglib2.0-0
        sudo apt-get install -y libgtk-3-0
        sudo apt-get install -y libnspr4
        sudo apt-get install -y libpango-1.0-0
        sudo apt-get install -y libpangocairo-1.0-0
        sudo apt-get install -y libstdc++6
        sudo apt-get install -y libx11-6
        sudo apt-get install -y libx11-xcb1
        sudo apt-get install -y libxcomposite1
        sudo apt-get install -y libxcursor1
        sudo apt-get install -y libxdamage1
        sudo apt-get install -y libxext6
        sudo apt-get install -y libxfixes3
        sudo apt-get install -y libxi6
        sudo apt-get install -y libxrandr2
        sudo apt-get install -y libxrender1
        sudo apt-get install -y libxss1
        sudo apt-get install -y libxtst6
        sudo apt-get install -y ca-certificates
        sudo apt-get install -y fonts-liberation
        sudo apt-get install -y libappindicator3-1
        sudo apt-get install -y libnss3
        sudo apt-get install -y lsb-release
        sudo apt-get install -y xdg-utils
        sudo apt-get install -y libatspi2.0-0
        sudo apt-get install -y libatk-bridge2.0-0
        sudo apt-get install -y libdrm2
        sudo apt-get install -y libgtk-3-common
        sudo apt-get install -y libharfbuzz0b
        sudo apt-get install -y libpangoft2-1.0-0

    - name: Starting CRD
      run: |
        sudo /opt/google/chrome-remote-desktop/start-host --code=${{ github.event.inputs.authcode }} --pin=${{ github.event.inputs.pincode }}

    - name: Keep Alive
      run: |
        while true; do
          sleep 3600
        done
