name: Windows-CRD

on:
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Initializing Setup
      run: |
        # Disable Windows Firewall
        Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
        
        # Install Chrome Remote Desktop Host
        $P = $env:TEMP + '\chromeremotedesktophost.msi'
        Invoke-WebRequest 'https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi' -OutFile $P
        Start-Process $P -Wait
        Remove-Item $P
        
        # Install Google Chrome
        $P = $env:TEMP + '\chrome_installer.exe'
        Invoke-WebRequest 'https://dl.google.com/chrome/install/latest/chrome_installer.exe' -OutFile $P
        Start-Process -FilePath $P -Args '/install' -Verb RunAs -Wait
        Remove-Item $P

    - name: Starting CRD
      run: |
        # Start the Chrome Remote Desktop Host
        & 'C:\Program Files (x86)\Google\Chrome\Application\chrome-remote-desktop-host.exe' --auth-code=${{ github.event.inputs.authcode }} --pin=${{ github.event.inputs.pincode }}

    - name: Keep Alive
      run: |
        # Keep the session alive
        while (1) { Start-Sleep -Seconds 60 }
